add in version output and also improve install re-run

diff --git a/packages/composer-website/installers/hlfv1/install.sh.in b/packages/composer-website/installers/hlfv1/install.sh.in
--- a/packages/composer-website/installers/hlfv1/install.sh.in
+++ b/packages/composer-website/installers/hlfv1/install.sh.in
@@ -7,6 +7,39 @@ fi
 #!/bin/bash
 set -ev
 
+# Docker stop function
+function stop()
+{
+P1=$(docker ps -q)
+if [ "${P1}" != "" ]; then
+  echo "Killing all running containers"  &2> /dev/null
+  docker kill ${P1}
+fi
+
+P2=$(docker ps -aq)
+if [ "${P2}" != "" ]; then
+  echo "Removing all containers"  &2> /dev/null
+  docker rm ${P2} -f
+fi
+}
+
+
+while getopts ":x" opt; do
+  case $opt in
+    x)
+      echo "Stopping all docker containers" >&2
+      stop
+      exit
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit
+      ;;
+  esac
+done
+
+
+
 # Get the current directory.
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
@@ -27,12 +60,9 @@ PAYLOAD_START=$((PAYLOAD_LINE + 1))
 echo PAYLOAD_START=${PAYLOAD_START}
 tail -n +${PAYLOAD_START} "${SOURCE}" | tar -xzf -
 
-# Kill and remove any running Docker containers.
-docker-compose -p composer kill
-docker-compose -p composer down --remove-orphans
+# stop all the docker containers
+stop
 
-# Kill any other Docker containers.
-docker ps -aq | xargs docker rm -f || echo 'All removed'
 
 # run the fabric-dev-scripts to get a running fabric
 ./fabric-dev-servers/downloadFabric.sh
